### ISSUE TITLE
[Проблема] Не создается экземпляр клиента.

### ISSUE THREAD

**Issue by DanGSun** [MarshalX/yandex-music-api#3]
```
2019-07-13 02:25:07,855 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth.yandex.ru:443
***/venv/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2019-07-13 02:25:08,351 - urllib3.connectionpool - DEBUG - https://oauth.yandex.ru:443 "POST /token HTTP/1.1" 200 125
2019-07-13 02:25:08,364 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.music.yandex.net:443
***/venv/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2019-07-13 02:25:09,168 - urllib3.connectionpool - DEBUG - https://api.music.yandex.net:443 "GET /account/status HTTP/1.1" 200 None
Traceback (most recent call last):
  File "***/PycharmProjects/RadioListener_CLI/listener.py", line 42, in <module>
    muscle = Client(db["username"], db["password"])
  File "***/venv/lib/python3.7/site-packages/yandex_music/client.py", line 67, in __init__
    self.account = self.account_status().account
  File "***/PycharmProjects/RadioListener_CLI/venv/lib/python3.7/site-packages/yandex_music/client.py", line 159, in account_status
    return Status.de_json(result, self)
  File "***/PycharmProjects/RadioListener_CLI/venv/lib/python3.7/site-packages/yandex_music/status/status.py", line 94, in de_json
    data['account'] = Account.de_json(data.get('account'), client)
  File "***/PycharmProjects/RadioListener_CLI/venv/lib/python3.7/site-packages/yandex_music/status/account.py", line 104, in de_json
    return cls(client=client, **data)
TypeError: __init__() missing 1 required positional argument: 'birthday'
```

**Comment by MarshalX** [comment]
Это было исправлено пользователем под ником @eugenweissbart несколько дней назад. [Вот его ПР](https://github.com/MarshalX/yandex-music-api/pull/1), просто не было обновлено на PyPi.

**Comment by MarshalX** [comment]
Обновил PyPi https://github.com/MarshalX/yandex-music-api/commit/7c19a602efd6207d17b9d8b4605a6700720e69c1
