### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by victorvorobev** [MarshalX/yandex-music-api#465]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

```
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'advertisement': 'Оформите постоянную подписку – первый месяц бесплатно!', 'bar_below': {'alert_id': 'xxx', 'text': 'тест Подписка скоро законч
ится. А вместе с ней закончатся музыка и подкасты без ограничений. Не надо так.', 'bg_color': '#FF5038', 'text_color': '#FFFFFF', 'alert_type': 'Churn_SubscriptionEnd_Music', 'button': {'text': 'Оформить 
подписку', 'bg_color': '#FFFFFF', 'text_color': '#191919', 'uri': 'https://plus.yandex.ru/?source=music_web_churn_subscriptionend'}, 'close_button': False}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/viktor.vorobev/projects/spothiefy/venv/lib/python3.8/site-packages/yandex_music/client.py", line 118, in from_credentials
    token = cls(*args, **kwargs).generate_token_by_username_and_password(username, password,
  File "/home/viktor.vorobev/projects/spothiefy/venv/lib/python3.8/site-packages/yandex_music/client.py", line 34, in wrapper
    result = method(*args, **kwargs)
  File "/home/viktor.vorobev/projects/spothiefy/venv/lib/python3.8/site-packages/yandex_music/client.py", line 183, in generate_token_by_username_and_password
    result = self._request.post(url, data, timeout=timeout, *args, **kwargs)
  File "/home/viktor.vorobev/projects/spothiefy/venv/lib/python3.8/site-packages/yandex_music/utils/request.py", line 246, in post
    result = self._request_wrapper('POST', url, headers=self.headers, proxies=self.proxies, data=data,
  File "/home/viktor.vorobev/projects/spothiefy/venv/lib/python3.8/site-packages/yandex_music/utils/request.py", line 198, in _request_wrapper
    raise BadRequest(message)
yandex_music.exceptions.BadRequest: invalid_grant login or password is not valid

```

**Comment by MarshalX** [comment]
Спасибо. Вероятно у вас была не последняя версия библиотеки
