### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by msazanov** [MarshalX/yandex-music-api#467]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

```
2021-09-07 12:07:56.457 T:59077    INFO <general>: initializing python engine.
2021-09-07 12:07:56.837 T:59077 WARNING <general>: [---] codec: aac, high_res: True
2021-09-07 12:07:57.123 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:07:57.123 T:59077   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:07:57.123 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:07:57.124 T:59077   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:07:57.124 T:59077 WARNING <general>: [---] [Yandex music plugin] authorized: True, mode: ['search'], args: {'mode': ['search'], 'title': ['Search']}
2021-09-07 12:08:33.133 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.133 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.134 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.135 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.136 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.137 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'VIDEO_ALLOWED'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'podcast_episode_type': 'full', 'track_sharing_flag': 'VIDEO_ALLOWED'}
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:33.138 T:59077   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'podcast_episode_type': 'full', 'track_sharing_flag': 'VIDEO_ALLOWED'}
                                                   
2021-09-07 12:08:33.139 T:59077   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'order'
                                                   Traceback (most recent call last):
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 666, in <module>
                                                       main()
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 511, in main
                                                       build_search(client)
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 421, in build_search
                                                       results = getSortedResults(client.search(searchString))
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 627, in getSortedResults
                                                       tmp = [(getattr(search, field).order, field) for field in fields]
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 627, in <listcomp>
                                                       tmp = [(getattr(search, field).order, field) for field in fields]
                                                   AttributeError: 'NoneType' object has no attribute 'order'
                                                   -->End of Python script error report<--
                                                   
2021-09-07 12:08:33.151 T:56987    INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-09-07 12:08:33.187 T:59077    INFO <general>: Python interpreter stopped
2021-09-07 12:08:33.203 T:59075   ERROR <general>: GetDirectory - Error getting plugin://plugin.yandex-music/?mode=search&title=Search
2021-09-07 12:08:33.217 T:56980   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.yandex-music/?mode=search&title=Search) failed
2021-09-07 12:08:33.256 T:59255    INFO <general>: initializing python engine.
2021-09-07 12:08:33.336 T:56987    INFO <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 300 ms Periodsize 100 ms
2021-09-07 12:08:33.645 T:59255 WARNING <general>: [---] codec: aac, high_res: True
2021-09-07 12:08:34.141 T:59255   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:34.141 T:59255   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:08:34.141 T:59255   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:34.141 T:59255   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:08:34.141 T:59255 WARNING <general>: [---] [Yandex music plugin] authorized: True, mode: None, args: {}
2021-09-07 12:08:34.717 T:59259   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:34.717 T:59259   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:08:34.717 T:59259   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:34.717 T:59259   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:08:34.902 T:59255    INFO <general>: CPythonInvoker(27, /home/random/.kodi/addons/plugin.yandex-music/plugin.py): script successfully run
2021-09-07 12:08:34.902 T:59255    INFO <general>: CPythonInvoker(27, /home/random/.kodi/addons/plugin.yandex-music/plugin.py): waiting on thread 140006471497472
2021-09-07 12:08:36.288 T:59259   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:08:36.288 T:59259   ERROR <general>: Type: <class 'yandex_music.account.plus.Plus'>; kwargs: {'migrated': False}
                                                   
2021-09-07 12:08:36.353 T:59255    INFO <general>: Python interpreter stopped




```

В kodi 19 при помощи плагина https://github.com/Angel777d/kodi.plugin.yandex-music не получается воспроизвести музыку из поиска, mixes, User Playlist

**Comment by MarshalX** [comment]
Спасибо. Перенес в другой ишус
