### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by json1c** [MarshalX/yandex-music-api#533]
**Опишите ошибку**
При установке возникает ошибка " AttributeError: 'PathDistribution' object has no attribute '_normalized_name' "

**Воспроизведение**
Шаги для воспроизведения бага:
1. Установить библиотеку

**Логи**
```
~                                                                                                        at 15:22:01
> pip install yandex-music --upgrade
Defaulting to user installation because normal site-packages is not writeable
Collecting yandex-music
  Downloading yandex-music-2.0.1.tar.gz (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 139.3 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-mf_dpt0m/yandex_music.egg-info
      writing /tmp/pip-pip-egg-info-mf_dpt0m/yandex_music.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-mf_dpt0m/yandex_music.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-mf_dpt0m/yandex_music.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-mf_dpt0m/yandex_music.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-mf_dpt0m/yandex_music.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6de46rpy/yandex-music_da51b7b159884c73b0b97bb35d1462c5/setup.py", line 21, in <module>
          setup(
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 298, in run
          self.find_sources()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 305, in find_sources
          mm.run()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 540, in run
          self.add_defaults()
        File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 577, in add_defaults
          sdist.add_defaults(self)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 226, in add_defaults
          self._add_defaults_python()
        File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 111, in _add_defaults_python
          build_py = self.get_finalized_command('build_py')
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 298, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 858, in get_command_obj
          klass = self.get_command_class(command)
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 948, in get_command_class
          eps = metadata.entry_points(group='distutils.commands', name=command)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1009, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
          ordered = sorted(eps, key=by_group)
        File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1006, in <genexpr>
          eps = itertools.chain.from_iterable(
        File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
          k = key(element)
      AttributeError: 'PathDistribution' object has no attribute '_normalized_name'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by MarshalX** [comment]
Вот тут по этому поводу обсуждают что-то https://github.com/pypa/setuptools/issues/3452

**Comment by MarshalX** [comment]
Если нужно быстрое решение, то вот: "Downgrade to Setuptools<60.9."
