### ISSUE TITLE
Ошибка при попытке получить очередь треков

### ISSUE THREAD

**Issue by 0ft3n** [MarshalX/yandex-music-api#538]
**Опишите ошибку**
При попытке использовать client.queue(str) получаем ошибку:
TypeError: Queue.__init__() missing 1 required positional argument: 'current_index'

**Воспроизведение**
1. Инициализируем клиент
2. Получаем первую очередь из списка client.queues_list()
3. Пытаемся использовать client.queue(str) или queue.fetch_queue()
4. Видим ошибку

**Ожидаемое поведение**
Получение объекта Queue

**Логи**
Traceback (most recent call last):
```
  File "C:\Users\dmitr\PycharmProjects\ymTest\main.py", line 12, in <module>
    lastq = last_queue.fetchQueue()
  File "C:\Users\dmitr\PycharmProjects\ymTest\venv\lib\site-packages\yandex_music\queue\queue_item.py", line 34, in fetch_queue
    return self.client.queue(self.id, *args, **kwargs)
  File "C:\Users\dmitr\PycharmProjects\ymTest\venv\lib\site-packages\yandex_music\client.py", line 66, in wrapper
    result = method(*args, **kwargs)
  File "C:\Users\dmitr\PycharmProjects\ymTest\venv\lib\site-packages\yandex_music\client.py", line 2529, in queue
    return Queue.de_json(result, self)
  File "C:\Users\dmitr\PycharmProjects\ymTest\venv\lib\site-packages\yandex_music\queue\queue.py", line 59, in de_json
    return cls(client=client, **data)
TypeError: Queue.__init__() missing 1 required positional argument: 'current_index'
```

**Дополнительная информация**
![image](https://user-images.githubusercontent.com/84244393/184733217-0789a719-c148-4892-8819-4538e09be53d.png)

**Comment by MarshalX** [comment]
Можете включить дебаг логи и показать ответ от сервера?

**Comment by MarshalX** [comment]
Доп информация не получена
