### ISSUE TITLE
Ошибка при попытке получить текст песни 

### ISSUE THREAD

**Issue by VitnessYT** [MarshalX/yandex-music-api#596]
**Опишите ошибку**
При вызове track.get_lirycs, выдается ошибка. Причем не связанная с тем, найден ли сам текст

**Воспроизведение**
Шаги для воспроизведения бага:
1. Скопировать код из примеров в документации https://yandex-music.readthedocs.io/en/main/examples.lyrics_playing_track.html (или сделать любой свой с попыткой загрузить текст песни)
2. Запустить код (вызвать метод yandex_music.track.track.Track.get_lyrics)
3. Увидеть ошибку

**Ожидаемое поведение**
Текст песни либо ошибка о том, что текст отсутствует.

**Логи**
```
Traceback (most recent call last):
  File "...\main.py", line 47, in <module>
    lyrics = last_track.get_lyrics('LRC')
  File "...\venv\lib\site-packages\yandex_music\track\track.py", line 182, in get_lyrics
    return self.client.tracks_lyrics(self.id, *args, **kwargs)
  File "...\venv\lib\site-packages\yandex_music\client.py", line 70, in wrapper
    result = method(*args, **kwargs)
  File "...\venv\lib\site-packages\yandex_music\client.py", line 611, in tracks_lyrics
    return TrackLyrics.de_json(result, self)
  File "...\venv\lib\site-packages\yandex_music\track\track_lyrics.py", line 70, in de_json
    data['major'] = LyricsMajor.de_json(data.get('major'), client)
  File "...\venv\lib\site-packages\yandex_music\track\lyrics_major.py", line 46, in de_json
    return cls(client=client, **data)
TypeError: LyricsMajor.__init__() missing 1 required positional argument: 'pretty_name'
```

**Comment by MarshalX** [comment]
А может есть ID трека с которым возникает ошибка при получении текста?

**Comment by VitnessYT** [comment]
Например, 33311009. Но в принципе разницы нет, такое на любом треке.

Еще один пример кода, с выводом айдишек.

```python
from yandex_music import Client

client = Client("token...").init()

for i, track in enumerate(client.users_likes_tracks()):
    if i == 5:
        break
    track = track.fetch_track()
    try:
        lyrics = track.get_lyrics('LRC')
    except Exception as e:
        print(f"{track.title}, id={track.id}, lyrics={track.lyrics_available} | error: {e}")
```

Вывод:
```
Yandex Music API v2.1.1, Copyright (C) 2019-2023 Ilya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3)

Showtime, id=64328778, lyrics=False | error: LyricsMajor.__init__() missing 1 required positional argument: 'pretty_name'
outside, id=39270299, lyrics=True | error: LyricsMajor.__init__() missing 1 required positional argument: 'pretty_name'
Statement, id=99292478, lyrics=True | error: LyricsMajor.__init__() missing 1 required positional argument: 'pretty_name'
Dysfunctional, id=37410064, lyrics=True | error: LyricsMajor.__init__() missing 1 required positional argument: 'pretty_name'
Lights, id=63379873, lyrics=False | error: LyricsMajor.__init__() missing 1 required positional argument: 'pretty_name'
```

**Comment by MarshalX** [comment]
@VitnessYT pip uninstall yandex_music
pip install git+https://github.com/MarshalX/yandex-music-api.git

помогло?

**Comment by VitnessYT** [comment]
Ну не особо))
```
Traceback (most recent call last):
  File "...\PycharmProjects\pythonProject\main2.py", line 9, in <module>
    lyrics = track.get_lyrics('TEXT')
  File "...\PycharmProjects\pythonProject\venv\lib\site-packages\yandex_music\track\track.py", line 182, in get_lyrics
    return self.client.tracks_lyrics(self.id, *args, **kwargs)
  File "...\PycharmProjects\pythonProject\venv\lib\site-packages\yandex_music\client.py", line 70, in wrapper
    result = method(*args, **kwargs)
  File "...\PycharmProjects\pythonProject\venv\lib\site-packages\yandex_music\client.py", line 611, in tracks_lyrics
    return TrackLyrics.de_json(result, self)
  File "...\PycharmProjects\pythonProject\venv\lib\site-packages\yandex_music\track\track_lyrics.py", line 72, in de_json
    return cls(client=client, **data)
TypeError: TrackLyrics.__init__() missing 1 required positional argument: 'writers'
```

**Comment by MarshalX** [comment]
> Ну не особо)) Но старая ошибка исправилась.
> 
> ```
> Traceback (most recent call last):
>   File "...\PycharmProjects\pythonProject\main2.py", line 9, in <module>
>     lyrics = track.get_lyrics('TEXT')
>   File "...\PycharmProjects\pythonProject\venv\lib\site-packages\yandex_music\track\track.py", line 182, in get_lyrics
>     return self.client.tracks_lyrics(self.id, *args, **kwargs)
>   File "...\PycharmProjects\pythonProject\venv\lib\site-packages\yandex_music\client.py", line 70, in wrapper
>     result = method(*args, **kwargs)
>   File "...\PycharmProjects\pythonProject\venv\lib\site-packages\yandex_music\client.py", line 611, in tracks_lyrics
>     return TrackLyrics.de_json(result, self)
>   File "...\PycharmProjects\pythonProject\venv\lib\site-packages\yandex_music\track\track_lyrics.py", line 72, in de_json
>     return cls(client=client, **data)
> TypeError: TrackLyrics.__init__() missing 1 required positional argument: 'writers'
> ```

а тут какой ID трека?

**Comment by VitnessYT** [comment]
64328778
Запускал на том же, просто убрал try-except для полной ошибки

```
Showtime, id=64328778, lyrics=False | error: TrackLyrics.__init__() missing 1 required positional argument: 'writers'
outside, id=39270299, lyrics=True | error: TrackLyrics.__init__() missing 1 required positional argument: 'writers'
Statement, id=99292478, lyrics=True | error: TrackLyrics.__init__() missing 1 required positional argument: 'writers'
Dysfunctional, id=37410064, lyrics=True | error: TrackLyrics.__init__() missing 1 required positional argument: 'writers'
Lights, id=63379873, lyrics=False | error: TrackLyrics.__init__() missing 1 required positional argument: 'writers'
```

**Comment by MarshalX** [comment]
> 64328778

у меня другая ошибка

"""
    raise NotFoundError(message)
yandex_music.exceptions.NotFoundError: {'name': 'No lyrics found for track', 'message': ''} 
"""

**Comment by MarshalX** [comment]
Какой токен используется и используется ли? Как токен получался? Есть ли платная подписка на аккаунте?

**Comment by VitnessYT** [comment]
bearer (или о чем речь?)
Через этот способ https://github.com/MarshalX/yandex-music-api/discussions/513#discussioncomment-2729781
Подписки нет, но попробовал сейчас на другом аккаунте с подпиской - тот же результат

**Comment by MarshalX** [comment]
@glebliutsko призывая тебя как автора этой фичи. У меня не воспроизводится. В ТГ боте тоже таких ошибок нет

**Comment by VitnessYT** [comment]
Подменив
```python
        return cls(client=client, **data)
```
на
```python
        return cls(client=client, writers=None, **data)
```
Смог вытащить словарь с ссылкой на скачивание файла, в котором текст
```
Подключите подписку на Плюс, чтобы видеть тексты песен
```
Так что возможно проблема все же в этом.
Хотя токен используется от аккаунта с подпиской, непонятно.

**Comment by VitnessYT** [comment]
А не, неправда. Я второй аккаунт тоже без подписки чекнул. С подпиской где-то затерялся. Завтра проверю и закрою, скорее всего проблемы нет.

**Comment by MarshalX** [comment]
@VitnessYT отличная инфа! Нужно подумать стоит ли это обрабатывать библиотекой. Такие исключения не дают понятия что необходиима подписка. Но и яндекс молодцы. Вместо ошибки выдают кусок правильного ответа где вместо текста заглушка про подписку.

cc @glebliutsko

**Comment by MarshalX** [comment]
Я в боте использую такую проверку на подписку. Вот почему не видно в нем ошибок:

https://github.com/MarshalX/yandex-music-api/blob/110a6e0318bf052923c1f6948718025b7c851a0a/examples/proxy.py#L16-L17C14

**Comment by MarshalX** [comment]
но мне жаловались пользователи что бот думает что у них нет подписки, хотя это не так

**Comment by MarshalX** [comment]
> Я в боте использую такую проверку на подписку. Вот почему не видно в нем ошибок:
> 
> https://github.com/MarshalX/yandex-music-api/blob/110a6e0318bf052923c1f6948718025b7c851a0a/examples/proxy.py#L16-L17C14

так, а там случайно not не потерялся? вместо "and client.me.plus" надо "and not client.me.plus"
