### ISSUE TITLE
Ошибка при вызове метода client.search

### ISSUE THREAD

**Issue by json1c** [MarshalX/yandex-music-api#597]
**Опишите ошибку**
Не работает поиск методом `client.search()`

**Воспроизведение**
`search_results = await client.search(query, type_="track")`

**Ожидаемое поведение**
Работающий поиск

**Логи**
```
  File "/home/userX/botX/tgbot/services/downloaders/yandex_music_downloader.py", line 28, in search_tracks
    search_results = await self.client.search(query, type_="track")
  File "/home/userX/.local/lib/python3.10/site-packages/yandex_music/client_async.py", line 74, in wrapper
    result = await method(*args, **kwargs)
  File "/home/userX/.local/lib/python3.10/site-packages/yandex_music/client_async.py", line 772, in search
    result = await self._request.get(url, params, *args, **kwargs)
  File "/home/userX/.local/lib/python3.10/site-packages/yandex_music/utils/request_async.py", line 273, in get
    result = await self._request_wrapper(
  File "/home/userX/.local/lib/python3.10/site-packages/yandex_music/utils/request_async.py", line 252, in _request_wrapper
    raise NetworkError(f'{message} ({resp.status}): {content}')
yandex_music.exceptions.NetworkError: {'name': 'unknown', 'message': 'omitted'}  (500): b'{"invocationInfo":{"req-id":"1684345950255961-3418765297824562155","hostname":"music-stable-back-sas-30.sas.yp-c.yandex.net","exec-duration-millis":0},"error":{"name":"unknown","message":"omitted"}}'
```

**Дополнительная информация**
Добавьте любой другой контекст о проблеме здесь.

**Comment by MarshalX** [comment]
А клиент как создаётся?

**Comment by json1c** [comment]
> А клиент как создаётся?

```    def __init__(self):
        self.client = ClientAsync(config.yandex.token)```

**Comment by MarshalX** [comment]
@json1c а как был получен токен?

**Comment by json1c** [comment]
> @json1c а как был получен токен?

Через https://music-yandex-bot.ru/

Думаешь, токен невалидный или не хватает прав?

**Comment by MarshalX** [comment]
@json1c А откуда запрос делаешь? С какой страны? А подписка на аккаунте есть?

**Comment by json1c** [comment]
> @json1c А откуда запрос делаешь? С какой страны? А подписка на аккаунте есть?

Страна - Германия, подписки нет

**Comment by MarshalX** [comment]
@json1c Вот в этом и проблема может быть. Нук сделай или без токена запрос, без автризации вовсе, или с СНГ прокси

**Comment by json1c** [comment]
> @json1c Вот в этом и проблема может быть. Нук сделай или без токена запрос, без автризации вовсе, или с СНГ прокси

Без токена
```
>>> from yandex_music import Client
>>> client = Client()
Yandex Music API v2.1.1, Copyright (C) 2019-2023 Ilya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3)

>>> client.search("Rammstein")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yandex_music/client.py", line 70, in wrapper
    result = method(*args, **kwargs)
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yandex_music/client.py", line 766, in search
    result = self._request.get(url, params, *args, **kwargs)
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yandex_music/utils/request.py", line 263, in get
    result = self._request_wrapper(
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yandex_music/utils/request.py", line 242, in _request_wrapper
    raise NetworkError(f'{message} ({resp.status_code}): {resp.content}')
yandex_music.exceptions.NetworkError: {'name': 'unknown', 'message': 'omitted'}  (500): b'{"invocationInfo":{"req-id":"1684409462368010-4988538790264802953","hostname":"music-stable-back-sas-78.sas.yp-c.yandex.net","exec-duration-millis":0},"error":{"name":"unknown","message":"omitted"}}'
```

Сейчас с прокси попробую

**Comment by json1c** [comment]
а если просто купить подписку, проблема пройдет?

**Comment by MarshalX** [comment]
@json1c пока что непонятно

**Comment by MarshalX** [comment]
@glebliutsko

**Comment by MarshalX** [comment]
> а если просто купить подписку, проблема пройдет?

Проверил. Да, мой аккаунт с подпиской из Польши работает нормально. Без подписки 500 ошибка. Без авторизации 500 ошибка

**Comment by json1c** [comment]
> > а если просто купить подписку, проблема пройдет?
> 
> Проверил. Да, мой аккаунт с подпиской из Польши работает нормально. Без подписки 500 ошибка. Без авторизации 500 ошибка

Да, работает, тоже проверил
