### ISSUE TITLE
> @json1c Вот в этом и проблема может быть. Нук сделай или без токена запрос, без автризации вовсе, или с СНГ прокси

### ISSUE THREAD

**Issue by json1c** [MarshalX/yandex-music-api#598]
> @json1c Вот в этом и проблема может быть. Нук сделай или без токена запрос, без автризации вовсе, или с СНГ прокси

Без токена
```
>>> from yandex_music import Client
>>> client = Client()
Yandex Music API v2.1.1, Copyright (C) 2019-2023 Ilya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3)

>>> client.search("Rammstein")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yandex_music/client.py", line 70, in wrapper
    result = method(*args, **kwargs)
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yandex_music/client.py", line 766, in search
    result = self._request.get(url, params, *args, **kwargs)
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yandex_music/utils/request.py", line 263, in get
    result = self._request_wrapper(
  File "/home/eyesaver/.local/lib/python3.10/site-packages/yandex_music/utils/request.py", line 242, in _request_wrapper
    raise NetworkError(f'{message} ({resp.status_code}): {resp.content}')
yandex_music.exceptions.NetworkError: {'name': 'unknown', 'message': 'omitted'}  (500): b'{"invocationInfo":{"req-id":"1684409462368010-4988538790264802953","hostname":"music-stable-back-sas-78.sas.yp-c.yandex.net","exec-duration-millis":0},"error":{"name":"unknown","message":"omitted"}}'
```

_Originally posted by @json1c in https://github.com/MarshalX/yandex-music-api/issues/597#issuecomment-1552923322_

**Comment by json1c** [comment]
случайно
