### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by p166** [MarshalX/yandex-music-api#618]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!

```
Type: <class 'yandex_music.account.account.Account'>; kwargs: {'child': False, 'non_owner_family_member': False}
Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'masterhub': {'active_subscriptions': [], 'available_subscriptions': []}, 'has_options': [], 'userhash': '417f1d-DELETED'}

Traceback (most recent call last):
  File "/home/p166/.local/share/rhythmbox/plugins/yandex-music/yandex-music.py", line 29, in do_load
    if self.login_yandex():
  File "/home/p166/.local/share/rhythmbox/plugins/yandex-music/yandex-music.py", line 115, in login_yandex
    self.client = Client(token).init()
AttributeError: 'Client' object has no attribute 'init'



```

**Comment by MarshalX** [comment]
Обновите версию библиотеки
