### ISSUE TITLE
Новое неизвестное поле от API

### ISSUE THREAD

**Issue by CATIOR** [MarshalX/yandex-music-api#648]
### По просьбе из WARNING'a прикладываю отладочную информацию ниже, которая поможет Вам в разработке:

```
(myenv) 20:06 ~ $ python exportFromYandexMusic.py
Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
Type: <class 'yandex_music.account.status.Status'>; kwargs: {'advertisement': 'Оформите постоянную подписку – первый месяц бесплатно!', 'ba
r_below': {'alert_id': 'xxx', 'text': 'тест Подписка скоро закончится. А вместе с ней закончатся музыка и подкасты без ограничений. Не надо
 так.', 'bg_color': '#FF5038', 'text_color': '#FFFFFF', 'alert_type': 'Churn_SubscriptionEnd_Music', 'button': {'text': 'Оформить подписку'
, 'bg_color': '#FFFFFF', 'text_color': '#191919', 'uri': 'https://plus.yandex.ru/?source=music_web_churn_subscriptionend'}, 'close_button':
 False, 'close_button_styles': {}}}
Traceback (most recent call last):
  File "/home/princesseangine/exportFromYandexMusic.py", line 3, in <module>
    client = Client.from_credentials('[my_login_redacted]', '[my_password_redacted]')
  File "/home/princesseangine/myenv/lib/python3.10/site-packages/yandex_music/client.py", line 118, in from_credentials
    token = cls(*args, **kwargs).generate_token_by_username_and_password(username, password,
  File "/home/princesseangine/myenv/lib/python3.10/site-packages/yandex_music/client.py", line 34, in wrapper
    result = method(*args, **kwargs)
  File "/home/princesseangine/myenv/lib/python3.10/site-packages/yandex_music/client.py", line 183, in generate_token_by_username_and_passw
ord
    result = self._request.post(url, data, timeout=timeout, *args, **kwargs)
  File "/home/princesseangine/myenv/lib/python3.10/site-packages/yandex_music/utils/request.py", line 246, in post
    result = self._request_wrapper('POST', url, headers=self.headers, proxies=self.proxies, data=data,
  File "/home/princesseangine/myenv/lib/python3.10/site-packages/yandex_music/utils/request.py", line 198, in _request_wrapper
    raise BadRequest(message)
yandex_music.exceptions.BadRequest: invalid_grant login or password is not valid
```

Логин и пароль верные. Перепроверил.

**Comment by MarshalX** [comment]
Вы используете старую версию библиотеки которая больше не поддерживается. В новой версии входа по логину и паролю нет. Обновите библиотеку `pip install -U yandex-music` и получите токен самостоятельно
