### ISSUE TITLE
AttributeError: 'coroutine'

### ISSUE THREAD

**Issue by igorir3** [MarshalX/yandex-music-api#653]
Вначале думал, что это я косячу, но после увидел, такое же сообщение...
Короче, использование ClientAsync - смерти подобно
client.tracks -> coroutine
client.albums_with_tracks -> coroutine

А если делать на нормальном Client, то проблем нет

Вот пример подобной проблемы с альбомом:
```
Traceback (most recent call last):
  File "C:\Users\kiril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\GlaDos\main.py", line 103, in play
    playlist[ctx.author.id] = album.volumes[1:]
                              ^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'volumes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kiril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\kiril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kiril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'coroutine' object has no attribute 'volumes'
```

**Comment by MarshalX** [comment]
Ты точно не забыл вызывать методы с await?

**Comment by igorir3** [comment]
Да, точно, но я смог починить через asyncio
Подглядел у другого чела, он для вызоваклиента эту строчку: 
`YCLIENT = asyncio.run(ClientAsync(SETTINGS["YToken"]).init())`

+ Такой вопрос, раз уж ты тут... А как получить объект Track? А то я делаю в точь точь как в примере, но я получаю, только `list`

> Ты точно не забыл вызывать методы с await?

**Comment by MarshalX** [comment]
Если есть проблемы с понимаем async в Python рекомендую использовать синхронный клиент. При получении треков по IDs возвращается массив. Если был передан 1 track ID значит надо взять первый элемент массива с индексом 0. В основном README ведь есть пример

**Comment by igorir3** [comment]
Странно видно это мой косяк.

На счёт асинхроника: Я понимаю как он работает, поэтому сам не понимаю почему с await он отказался работать, а с asyncio работал без проблем :/ 

(Может я где то скобки забыл...)
